version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: adminJ
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    expose:
      - "3306"   
    volumes:
      - ./dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
  web:
   build: .
   command: python3 manage.py runserver 0.0.0.0:8000
   volumes:
    - .:/code
   restart: always
   ports:
    - "8000:8000"
   depends_on:
    - db 

