version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgresql:latest
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    expose:
      - "5432"   
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  web:
   build: .
   command: python3 manage.py runserver 0.0.0.0:8000
   volumes:
    - .:/code
   restart: always
   ports:
    - "8000:8000"
   depends_on:
    - db 
volumes:
  postgres_data: 