version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: adminJ
      MYSQL_USER: root
      MYSQL_PASSWORD: root
        
    #volumes:
      #- /.dbdata:/var/lib/mysql
    ports:
      - 33066:3306
    

